# Generated by Django 6.0.7 on 2026-07-27 07:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Le matricule doit contenir 3 à 20 caractères alphanumériques en majuscules.', regex='^[A-Z0-9]{3,20}$')])),
                ('nom', models.CharField(max_length=100)),
                ('postnom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10)),
                ('telephone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide. Format attendu: +243XXXXXXXXX', regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='agents/')),
                ('type_agent', models.CharField(choices=[('ENSEIGNANT', 'Enseignant'), ('ADMINISTRATIF', 'Administratif'), ('DISCIPLINE', 'Préfet de discipline')], max_length=20)),
                ('etat', models.BooleanField(default=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=100)),
                ('nationalite', models.CharField(default='Congolaise', max_length=50)),
                ('province_origine', models.CharField(blank=True, max_length=100)),
                ('territoire_origine', models.CharField(blank=True, max_length=100)),
                ('secteur', models.CharField(blank=True, max_length=100)),
                ('groupement', models.CharField(blank=True, max_length=100)),
                ('village_origine', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['nom', 'postnom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fonction',
                'verbose_name_plural': 'Fonctions',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='MessagingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envoi_bloque', models.BooleanField(default=False, help_text="Bloquer l'envoi de messages entre utilisateurs")),
                ('message_blocage', models.TextField(blank=True, help_text="Message affiché aux utilisateurs quand l'envoi est bloqué")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre de messagerie',
                'verbose_name_plural': 'Paramètres de messagerie',
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('niveau', models.CharField(max_length=50)),
                ('effectif', models.IntegerField(default=0, help_text="Nombre d'élèves dans la classe", validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('ARCHIVE', 'Archivé')], default='ACTIF', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['niveau', 'nom'],
                'indexes': [models.Index(fields=['niveau'], name='prestation__niveau_c1b911_idx'), models.Index(fields=['status'], name='prestation__status_aba75d_idx')],
                'constraints': [models.UniqueConstraint(fields=('nom', 'niveau'), name='unique_classe_nom_niveau')],
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Format du code: 2-4 lettres suivies de 1-3 chiffres (ex: MATH101)', regex='^[A-Z]{2,4}[0-9]{1,3}$')])),
                ('libelle', models.CharField(max_length=150)),
                ('coefficient', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['libelle'],
                'indexes': [models.Index(fields=['code'], name='prestation__code_2c2444_idx'), models.Index(fields=['actif'], name='prestation__actif_376ba5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Mois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('mois_num', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mois',
                'verbose_name_plural': 'Mois',
                'ordering': ['annee', 'mois_num'],
                'constraints': [models.UniqueConstraint(fields=('mois_num', 'annee'), name='unique_mois_annee')],
            },
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_arrivee', models.TimeField()),
                ('heure_depart', models.TimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('PRESENT', 'Présent'), ('RETARD', 'Retard'), ('ABSENT', 'Absent'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], max_length=20)),
                ('observation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestations', to='prestation.agent')),
            ],
            options={
                'verbose_name': 'Prestation',
                'verbose_name_plural': 'Prestations',
                'ordering': ['-date', '-heure_arrivee'],
            },
        ),
        migrations.CreateModel(
            name='PrestationEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('observation', models.TextField(blank=True, null=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestations', to='prestation.classe')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestations', to='prestation.cours')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestations_cours', to='prestation.prestation')),
            ],
            options={
                'verbose_name': 'Prestation Enseignant',
                'verbose_name_plural': 'Prestations Enseignants',
                'ordering': ['prestation__date', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Remarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('MESSAGE', 'Message'), ('APPROBATION', "Demande d'approbation"), ('NOTIFICATION', 'Notification')], default='MESSAGE', max_length=20)),
                ('sujet', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarques_recues', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarques_envoyees', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='prestation.remarque')),
            ],
            options={
                'verbose_name': 'Remarque',
                'verbose_name_plural': 'Remarques',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['nom'], name='prestation__nom_a1bd6b_idx')],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='prestation.service'),
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('SECRETAIRE', 'Secrétaire'), ('ENSEIGNANT', 'Enseignant'), ('PREFET', 'Préfet de discipline'), ('SURVEILLANT', 'Surveillant')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('must_change_password', models.BooleanField(default=True, help_text="Indique si l'utilisateur doit changer son mot de passe à la prochaine connexion")),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur', to='prestation.agent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('MESSAGE', 'Message'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('object_repr', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'activité",
                'verbose_name_plural': "Journaux d'activité",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'model_name'], name='prestation__action_7c0726_idx'), models.Index(fields=['actor', 'created_at'], name='prestation__actor_i_f8b6f3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='prestation',
            index=models.Index(fields=['agent', 'date'], name='prestation__agent_i_59c215_idx'),
        ),
        migrations.AddIndex(
            model_name='prestation',
            index=models.Index(fields=['date'], name='prestation__date_d71203_idx'),
        ),
        migrations.AddIndex(
            model_name='prestation',
            index=models.Index(fields=['statut'], name='prestation__statut_f2decd_idx'),
        ),
        migrations.AddConstraint(
            model_name='prestation',
            constraint=models.UniqueConstraint(fields=('agent', 'date'), name='unique_prestation_agent_date'),
        ),
        migrations.AddIndex(
            model_name='prestationenseignant',
            index=models.Index(fields=['cours'], name='prestation__cours_i_877294_idx'),
        ),
        migrations.AddIndex(
            model_name='prestationenseignant',
            index=models.Index(fields=['classe'], name='prestation__classe__959557_idx'),
        ),
        migrations.AddConstraint(
            model_name='prestationenseignant',
            constraint=models.UniqueConstraint(fields=('prestation', 'cours', 'classe'), name='unique_prestation_cours_classe'),
        ),
        migrations.AddIndex(
            model_name='remarque',
            index=models.Index(fields=['categorie', 'lu'], name='prestation__categor_f0abe7_idx'),
        ),
        migrations.AddIndex(
            model_name='remarque',
            index=models.Index(fields=['expediteur', 'destinataire'], name='prestation__expedit_8565be_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['matricule'], name='prestation__matricu_35187c_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['type_agent'], name='prestation__type_ag_6749f6_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['service'], name='prestation__service_a646e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_agent_email'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['role'], name='prestation__role_bc5943_idx'),
        ),
    ]
