# Generated by Django 6.0.7 on 2026-07-28 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPrestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('heure_ouverture', models.TimeField(blank=True, null=True)),
                ('heure_fermeture', models.TimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée')], default='EN_COURS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloture_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_cloturees', to='prestation.utilisateur')),
                ('ouvert_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_ouvertes', to='prestation.utilisateur')),
            ],
            options={
                'verbose_name': 'Session de Prestation',
                'verbose_name_plural': 'Sessions de Prestation',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='prestation',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestations', to='prestation.sessionprestation'),
        ),
        migrations.AddIndex(
            model_name='sessionprestation',
            index=models.Index(fields=['date'], name='prestation__date_61cdbc_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionprestation',
            index=models.Index(fields=['statut'], name='prestation__statut_e11ce2_idx'),
        ),
    ]
