# Generated by Django 6.0.7 on 2026-07-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestation', '0002_sessionprestation_prestation_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='mot_de_passe_temporaire',
            field=models.CharField(blank=True, default='', help_text="Mot de passe temporaire visible par l'administrateur (effacé après changement par l'utilisateur)", max_length=100),
        ),
    ]
