# Generated by Django 6.0.7 on 2026-07-30 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestation', '0003_utilisateur_mot_de_passe_temporaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='telephone',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide. Format attendu: +243 81 234 5678', regex='^\\+?[\\d\\s\\-\\(\\)]{8,20}$')]),
        ),
    ]
