# Generated by Django 6.0.7 on 2026-07-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestation', '0004_alter_agent_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionprestation',
            name='heure_limite',
            field=models.TimeField(blank=True, help_text="Heure limite pour arriver à l'heure (après cette heure, l'agent est en retard)", null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('SECRETAIRE', 'Secrétaire'), ('ENSEIGNANT', 'Enseignant'), ('AGENT', 'Agent')], max_length=20),
        ),
    ]
