# Generated by Django 6.0.7 on 2026-08-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestation', '0006_rename_agent_to_personnel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnel',
            options={'ordering': ['nom', 'postnom', 'prenom'], 'verbose_name': 'Personnel', 'verbose_name_plural': 'Personnels'},
        ),
        migrations.RenameIndex(
            model_name='personnel',
            new_name='prestation__matricu_0ea315_idx',
            old_name='prestation__matricu_35187c_idx',
        ),
        migrations.RenameIndex(
            model_name='personnel',
            new_name='prestation__type_ag_9f135a_idx',
            old_name='prestation__type_ag_6749f6_idx',
        ),
        migrations.RenameIndex(
            model_name='personnel',
            new_name='prestation__service_5ef7cb_idx',
            old_name='prestation__service_a646e6_idx',
        ),
        migrations.AlterField(
            model_name='prestation',
            name='statut',
            field=models.CharField(choices=[('PRESENT', 'Présent'), ('RETARD', 'Retard'), ('ABSENT', 'Absent'), ('EN_COURS', 'En cours')], max_length=20),
        ),
    ]
