# Generated by Django 6.0.7 on 2026-08-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestation', '0007_alter_personnel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestation',
            name='heure_arrivee',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
