# Generated by Django 6.0.7 on 2026-08-01 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestation', '0008_alter_prestation_heure_arrivee'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestationenseignant',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestationenseignant',
            name='valide',
            field=models.BooleanField(default=False, help_text='Indique si la prestation enseignant a été validée par un administrateur/secrétaire'),
        ),
        migrations.AddField(
            model_name='prestationenseignant',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestations_enseignants_validees', to='prestation.utilisateur'),
        ),
    ]
