# Generated by Django 6.0.7 on 2026-08-02 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestation', '0009_prestationenseignant_date_validation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personnel',
            new_name='Agent',
        ),
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['nom', 'postnom', 'prenom'], 'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
        migrations.RenameIndex(
            model_name='agent',
            new_name='prestation__matricu_35187c_idx',
            old_name='prestation__matricu_0ea315_idx',
        ),
        migrations.RenameIndex(
            model_name='agent',
            new_name='prestation__type_ag_6749f6_idx',
            old_name='prestation__type_ag_9f135a_idx',
        ),
        migrations.RenameIndex(
            model_name='agent',
            new_name='prestation__service_a646e6_idx',
            old_name='prestation__service_5ef7cb_idx',
        ),
    ]
