# Generated by Django 6.0.7 on 2026-08-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestation', '0010_rename_personnel_agent_alter_agent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Indique si le 2FA est activé pour cet utilisateur'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='two_factor_secret',
            field=models.CharField(blank=True, default='', help_text='Clé secrète pour Google Authenticator (2FA)', max_length=64),
        ),
    ]
