# Generated by Django 6.0.7 on 2026-08-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestation', '0011_utilisateur_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionprestation',
            name='date',
            field=models.DateField(),
        ),
    ]
