# Generated by Django 6.0.7 on 2026-08-03 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestation', '0012_alter_sessionprestation_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='prestation',
            name='unique_prestation_agent_date',
        ),
    ]
