# Generated by Django 6.0.7 on 2026-08-03 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestation', '0013_remove_prestation_unique_prestation_agent_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeTemporaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('est_utilise', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('expire_le', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_temporaires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code temporaire',
                'verbose_name_plural': 'Codes temporaires',
                'ordering': ['-cree_le'],
            },
        ),
    ]
