# Generated by Django 6.0.7 on 2026-08-04 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestation', '0014_codetemporaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestationenseignant',
            name='date_demarrage',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestationenseignant',
            name='demarree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestations_enseignants_demarrees', to='prestation.utilisateur'),
        ),
        migrations.AddField(
            model_name='prestationenseignant',
            name='en_cours',
            field=models.BooleanField(default=False, help_text='Indique si la prestation enseignant est en cours (démarrée) ou terminée'),
        ),
    ]
