# Generated by Django 6.0.7 on 2026-08-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestation', '0015_prestationenseignant_date_demarrage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestationenseignant',
            name='date_demarrage',
        ),
        migrations.RemoveField(
            model_name='prestationenseignant',
            name='demarree_par',
        ),
        migrations.RemoveField(
            model_name='prestationenseignant',
            name='en_cours',
        ),
    ]
