# Generated by Django 6.0.7 on 2026-08-05 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestation', '0016_remove_prestationenseignant_date_demarrage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='enseignant_responsable',
            field=models.ForeignKey(blank=True, help_text='Enseignant responsable de ce cours', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours_enseignants', to='prestation.agent'),
        ),
    ]
