# Generated by Django 6.0.7 on 2026-08-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestation', '0018_cours_heures_ponderation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='heures_ponderation',
        ),
    ]
