# Generated by Django 6.0.7 on 2026-08-05 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestation', '0019_remove_cours_heures_ponderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='heures_ponderation',
            field=models.IntegerField(default=0, help_text="Nombre total d'heures de prestation pour ce cours (ex: 60)", validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
